### ISSUE TITLE
Must pass PMIX_GET_REFRESH_CACHE to PMIX_Get when called from a tool.

### ISSUE THREAD

**Issue by dsolt** [openpmix/prrte#1035]
Thank you for taking the time to submit an issue!

## Background information

So I have a simple tool app that calls PMIX_tool_init() and then calls PMIx_Get() on PMIX_NSDIR, which is a job-level key.
I also pass in PMIX_JOB_INFO as an info, though I don't think that is required.

The call fails to find the value of PMIX_NSDIR. 

However, if I also pass in PMIX_GET_REFRESH_CACHE as an additional info, it finds it.  

If I run the same tool, but launch it as if it were a client (though it still calls PMIx_tool_init), it does not need the PMIX_GET_REFRESH_CACHE setting.

Any thoughts on why this is happening?

Ok, last really minor, very trivial piece of information that you can probably completely ignore.....   
yeah, I didn't actually try this with PRTE.  I built PRTE, but whenever I try to launch the servers it silently fails, exits, returns an error code, but doesn't print any messages and doesn't seem to start any processes.   So I'm using my own PMIx server (JSM).  So it could possibly be something JSM is doing wrong with setting up tool processes.   Would love for someone who knows how to start PRTE manually to try this experiement, or maybe someone who's name rhymes with Smalf just happens to be able to guess exactly what is going on here.

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

```

**Comment by rhc54** [comment]
Hmmm...looking at the tool_init functions, it appears we only request the initial job info if we are a client - which seems somewhat limiting, really. If we connected to a server, we might as well get whatever info they provided. I can change that.

Note that it will still ultimately depend on what the host environment chooses to provide to a connecting tool. I honestly don't recall what PRRTE does in that situation - I can check to see if it does in fact setup a session directory for a connecting tool. Might make sense to do so even though we don't provide any shmem info in it.

The refresh works, of course, because it forces the hash component to request all job-related info from the local server. Basically makes up for us not having requested it upon connection.

**Comment by rhc54** [comment]
I believe I now have tools getting all available info - at least for PRRTE, that will include `PMIX_NSDIR`. See if it now works for you.

I'm not sure why PRRTE is failing to launch for you. Can you provide more info on that (how you configured, etc.)?

**Comment by rhc54** [comment]
I believe PRRTE is failing to launch for you because you probably configured PMIx without HWLOC - yes? PMIx has become so dependent on topology info for its support (e.g., for device distances) that it now requires a hardware topology library. Although it technically doesn't have to be HWLOC, that's the only component we currently include - so HWLOC is required.

I have updated the configure logic to reflect that situation: https://github.com/openpmix/openpmix/pull/2243

**Comment by dsolt** [comment]
Thanks!  I will give it a try today!  It sounds like it will resolve me issue.  BTW, I did build with hwloc.  I figured out eventually that is what I needed to do, but something else must have been messed up.   I'll probably start from scratch and see what happens on that.

**Comment by rhc54** [comment]
Remember to build both PMIx and PRRTE `--with-hwloc` - PMIx should now error out without it. I think PRRTE isn't there yet.

**Comment by rhc54** [comment]
Pretty sure this is no longer an issue, but feel free to reopen if necessary
