### ISSUE TITLE
Proctable query not supported for indirect prun case

### ISSUE THREAD

**Issue by david-edwards-arm** [openpmix/prrte#1253]
### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)
Open MPI 5.0.x nightly snapshot [openmpi-v5.0.x-202203030340-563c565.tar.gz](https://download.open-mpi.org/nightly/open-mpi/v5.0.x/openmpi-v5.0.x-202203030340-563c565.tar.gz)

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)
Open MPI 5.0.x nightly snapshot [openmpi-v5.0.x-202203030340-563c565.tar.gz](https://download.open-mpi.org/nightly/open-mpi/v5.0.x/openmpi-v5.0.x-202203030340-563c565.tar.gz)

### Please describe the system on which you are running

* Operating system/version: Ubuntu 18.04
* Computer hardware: x86_64

-----------------------------

## Details of the problem

The context of the issue is indirect launch of a job under control of a debugger.
Broadly following the indirect.c example, inserting a PMIX_QUERY_PROC_TABLE query immediately following receipt of the Ready For Debug event results in an error code of PMIX_ERR_NOT_SUPPORTED.
Are there any plans to support querying the proctable for indirectly launched prun jobs in future?

**Comment by rhc54** [comment]
Just for clarity: you started a DVM, then used indirect to launch a job via prun - yes?

If so, then this sounds like a bug. I'll have to look into why the proctable query wasn't properly forwarded to the DVM.

**Comment by david-edwards-arm** [comment]
Hi @rhc54 yes that's correct - DVM started, then indirect launch of a job using prun as the launcher (broadly but not precisely following indirect.c).

**Comment by rhc54** [comment]
I've tracked this down to a combination of two problems:

* `prun` isn't a true server, it is a launcher and therefore currently cannot handle tool connections where the tool needs to have an ID provided to it. This doesn't impact the indirect.c example, but does preclude using something like `pquery`. I'll update the `pquery` tool to resolve this, and provide a better response to such a request than just `PRTE_ERR_NOT_SUPPORTED`
* since `prun` is a tool, it needs to relay the request to the DVM for processing, and then relay the response back to the requesting tool. This code path wasn't implemented yet.

I'm working on these now.
