### ISSUE TITLE
Tarball debugger examples fail to build

### ISSUE THREAD

**Issue by david-edwards-arm** [openpmix/prrte#1264]
### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)
Open MPI 5.0.0rc3

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)
Open MPI 5.0.0rc3

### Please describe the system on which you are running

* Operating system/version: Ubuntu 18.04
* Computer hardware: x86_64

-----------------------------

## Details of the problem

The `debugger.h` file is missing from the tarball.
Also the wrapper compiler is named `pmixcc` rather than the `pcc` referenced in the examples Makefile.

**Comment by rhc54** [comment]
You mean it is missing from the OMPI tarball? Just trying to understand - are you attempting to build the PRRTE debugger examples from the OMPI tarball? I'm not entirely sure that will work as they might not build the wrapper compiler at all, nor include everything needed for those examples.

**Comment by david-edwards-arm** [comment]
Right.. the PRRTE debugger examples are included in the OMPI tarball; the logic for determining which files are included seems to be in the PRRTE repo's examples/Makefile.include.
The tarball examples build, once debugger.h is included and pmixcc (from the built+installed OMPI) is used.

**Comment by rhc54** [comment]
I've fixed the missing header file, but I can do nothing about the wrapper compiler issue. The problem is that when you use the internal versions of the packages, `pmixcc` doesn't exist when PRRTE is being configured. Thus, PRRTE thinks it isn't available and doesn't setup the symlink to use it.

Best I can suggest is that you ask the OMPI folks to create the symlink on their side once all the packages have been built - possibly as an addition to the `mpirun` Makefile.
