### ISSUE TITLE
Java handling in src/prted/prte_app_parse.c

### ISSUE THREAD

**Issue by jsquyres** [openpmix/prrte#1335]
There is some Open MPI-specific Java handling in https://github.com/openpmix/prrte/blob/master/src/prted/prte_app_parse.c#L254-L376 (and elsewhere in that file).  I assume that this Open MPI-specific functionality is problematic in the PRTE core.

It's also incorrect if PRTE and Open MPI do not share the same libdir -- it adds PRTE's libdir, not Open MPI's libdir.  The end result is that the MPI jarfile won't be found.

Finally, it is also looking for a `shmem.jar` file, which does not exist (I'm guessing there was some discussion about creating that at one point and this code was written pro-actively... but then `shmem.jar` never actually got created).

Open MPI *does* need this functionality: i.e., look for ` java` token and then massage the app context a bit.  Should this functionality move to the OMPI schitzo component?  Or ...something else?

Any suggestion about how to get the correct libdir (i.e., Open MPI's libdir -- where the `mpi.jar` file will exist)?

**Comment by rhc54** [comment]
Hmmm...well, that captures a couple of issues. First, the code that is there is indeed incorrect for PRRTE. There is no such thing as a "PRRTE app", and thus we would never look for a `prte.jar` - and we obviously shouldn't be looking for `mpi.jar`. So we do need to remove it from that location. Probably the correct thing is to move that parsing down into the `schizo/ompi` plugin. I have no real idea about how you'd tell that component where to find the OMPI libdir. I suppose it has to be somewhere in the `LD_LIBRARY_PATH` or else the app wouldn't run when launched - yes? I wonder if you could track it down that way.

I suppose another approach is to add a `--with-ompi=foo` configure option, though that seems undesirable as it would lock each installation of PRRTE to a specific OMPI installation. Alternatively, you could require them to tell you the location on the cmd line, I suppose - perhaps as an MCA param so it could be set in the system or user default param file?

Second issue is support for Java applications in general. Back when we supported MapReduce we had a way of slurping up all the jar files and automatically forwarding them to the backend. Might need to dig back and find that code again - otherwise, we'll start a Java app and it will quite likely fail to find the necessary support on the backend. At least, that was our experience in those prior days.

**Comment by jsquyres** [comment]
Ok, thanks.  Let me talk this through with @bwbarrett and see what we want to do.

**Comment by rhc54** [comment]
I removed the errantcode from PRRTE here: https://github.com/openpmix/prrte/pull/1376

Note that you could resolve this problem by requiring the user to specifically list the jar file location - a change in behavior and perhaps burdensome, but workable. The MCA param may be your best solution.
