### ISSUE TITLE
Singletons?

### ISSUE THREAD

**Issue by rhc54** [openpmix/prrte#151]
Currently, the only way for an application process to connect to a PMIx server is by being spawned by that server - only tools have the logic to "discover" a PMIx server. This begs the question for PRRTE: how do we support singleton operations?

One possibility is to modify the client code to match that of a tool - i.e., if not given contact info, then search for it. However, this does beg some security issues that we deal with for tools, but not necessarily for apps. It also begins to blur the distinction between the two categories.

Another option would be to have the singleton spin off its own "prun" to support it ala what ORTE did - but that always left a sour taste in my mouth.

Any thoughts? My personal leaning would be to allow singletons to self-discover the local server, but to identify themselves as an app instead of a tool to make their intent clear for future places where we might want to differentiate them. For example, we allow a tool to drop a rendezvous file for subsequent attachment, but we don't provide that ability to an app.

@jjhursey @ggouaillardet ?

**Comment by ggouaillardet** [comment]
Are you talking of PMIx singleton ? Open MPI singleton ? both ?

I can only comment on the Open MPI singleton, so here are my thoughts.

Instead of fork&exec'ing `orted`, an ompi singleton has to fork&exec `prte`, and then connect to it.
At that stage, the singleton should know how to connect to the spawned `prte` (or it should not be hard to have `prte` communicate its url to the singleton(via `stdout` or a know file), so it does not have to discover the prte)

Then the singleton will likely do nothing (because the end user forgot to ask for an isolated singleton) or `MPI_Comm_spawn()` some other tasks.
At that stage, and I likely miss a big part of the picture, does it make any difference whether the singleton is an app or a tool from the PMIx server point of view ?

**Comment by rhc54** [comment]
I believe this has been resolved. PMIx_Init allows the client to continue "disconnected", returning the `PMIX_ERR_UNREACH` code. It is up to the layer above PMIx to decide what to do about it. If they want to continue running as a "singleton", then they can do so. If the process later wants to "comm_spawn", then the upper layer needs to direct PMIx to spawn an appropriate RTE support.
