### ISSUE TITLE
warn message about event base add

### ISSUE THREAD

**Issue by naughtont3** [openpmix/prrte#1601]
## Background information

Seeing warning message when running prte/pmix via `mpirun` with current Open MPI v5.0.x branch.  

```
[warn] Added a signal to event base 0x240331f0 with signals already added to event_base 0x2402d7f0.  Only one can have signals at a time with the epoll backend.  The base with the most recently added signal or the most recent event_base_loop() call gets preference; do not rely on this behavior in future Libevent versions.
```

### Versions

 - openmpi-br-v5.0.x:  d3a8e0ecae
 - openpmix submodule: e770a3362fcea61778b85b4c7cfb7044443c9490 3rd-party/openpmix (v4.2.2-9-ge770a336)
 - prrte submodule: 4262efb88da9292fbf5a29665dcc98eed49c751c 3rd-party/prrte (v3.0.0-2-g4262efb88d)

### Please describe the system on which you are running

* Operating system/version:
* Computer hardware:
* Network type:

-----------------------------

## Details of the problem

```shell
[naughton@login4.summit misc]$ prte --report-uri dvm.uri &
[1] 3030911
[naughton@login4.summit misc]$ DVM ready

[naughton@login4.summit misc]$ 
[naughton@login4.summit misc]$ prun --dvm-uri file:dvm.uri --np 4 hostname
login4
login4
login4
login4
[naughton@login4.summit misc]$ mpirun --np 4 hostname
login4
login4
login4
login4
[naughton@login4.summit misc]$ mpirun --dvm file:dvm.uri --np 4 hostname
[warn] Added a signal to event base 0x240331f0 with signals already added to event_base 0x2402d7f0.  Only one can have signals at a time with the epoll backend.  The base with the most recently added signal or the most recent event_base_loop() call gets preference; do not rely on this behavior in future Libevent versions.
login4
login4
login4
login4
```

**Comment by rhc54** [comment]
Really weird - I think I finally figured out what it must be complaining about, but I don't understand why it wouldn't _always_ complain as the condition exists every time one executes `prte` (in whatever form). Still, see if #1602 resolves the complaint.

**Comment by rhc54** [comment]
@naughtont3 any feedback on #1602?

**Comment by naughtont3** [comment]
> @naughtont3 any feedback on #1602?

@rhc54  Yep, that eliminates the event base add warning.  thanks

**Comment by rhc54** [comment]
So I tracked this down - first, to discover why you are seeing this message when the rest of us are not. Turns out that the warning is only emitted when libevent is built with debug enabled. Not sure how you managed to get that, but you must have it turned on somewhere.

Second, it is a legitimate problem. The full warning explains their behavior, which is all caused by them using a global variable to store the event base being used for signals. So if more than one event base attempts to capture a signal, things get very weird and unstable.

All I can do is provide a new attribute `PMIX_EXTERNAL_AUX_EVENT_BASE` to allow the host to pass their own event base down to the PMIx library for use when dealing with signals. This relies on them progressing that base, but one must assume they are doing so. Our signal capture callback functions don't involve calls to any internal things, so there should be no issue with lockup.

I have committed the changes to PMIx and PRRTE master branches - can you please verify it fixes this problem?

**Comment by naughtont3** [comment]
i'll refresh my ompi submodule pointers locally and do another test.  FWIW, the debug build was just by configuring ompi with `--enable-debug` and `--with-devel-headers`.  I guess that flows down to libevent's configure.

**Comment by rhc54** [comment]
Could be the difference - I build libevent separately and so never enable its debug. I also almost never build OMPI any more, so I wouldn't have seen it there.

**Comment by naughtont3** [comment]
So i still see the warning about multiple adds when running with `mpirun --dvm file:dvm.uri --np 1 hostname` (i.e., when reusing an existing PRTE DVM).  

The two spots where we call evsig_add().
 - setup_sighandler() (from prte.c:344), signal=SIGPIPE, handler=epipe_signal_callback, base="prte_event_base" (base=0x55555559dd60)
 - 
 - PMIx_tool_init() (from prte.c:475, under prun_common()), signal=SIGCHLD, handler=pmix_pfexec_globals.handler,  base="pmix_globals.evbase" (base=0x5555555a3e80)

So looks like we have an event base for prte and another for pmix. I'm not sure how the `PMIX_EXTERNAL_AUX_EVENT_BASE` would factor into this scenario as both evbases are in prte or pmix and not clear to me what impact the small mpirun+dvm changes that initialization.  Don't see much happening in the `opal_init_util()` we use in `mpirun.c` shim.

This is just a warning, but I'd like to grok why we get multiple event base errors only on this specific path.

**Comment by rhc54** [comment]
That doesn't look right - are you sure you updated the submodule? You are working with OMPI's main branch so you get the HEAD of the master branches from PMIx and PRRTE - correct?

Asking because `PMIx_tool_init` is using `pmix_globals.evauxbase`, which isn't what you are showing.

**Comment by naughtont3** [comment]
I am using ompi's v5.0.x branch and manually updated submodules to main

 - openpmix @ 91b011d5 Fix a typo in the macro backers and add a "stop" pt in deprecated.h
 - prte @ e8486bec19 Pass our event base for use by the PMIx library as an aux base
 - ompi @ f64038fb27 Merge pull request #112
 
But I will take another look and ensure the `pmix_globals.evauxbase` part.

**Comment by naughtont3** [comment]
Hmm, i see the  evauxbase.  Maybe there's something goofed in my build tree.

**Comment by naughtont3** [comment]
I think it may be the pfexec framework's init in `pmix_pfexec_base_open` that occurs during `PMIx_tool_init`

```
214     /* set to catch SIGCHLD events */
215     pmix_pfexec_globals.handler = (pmix_event_t *) malloc(sizeof(pmix_event_t));
216     pmix_event_set(pmix_globals.evbase, pmix_pfexec_globals.handler, SIGCHLD,
217                    PMIX_EV_SIGNAL | PMIX_EV_PERSIST, wait_signal_callback,
218                    pmix_pfexec_globals.handler);
```

This is using the `pmix_globals.evabase` for setting the SIGCHLD handler that generates the warning.

**Comment by rhc54** [comment]
ah, ok - let me take a peek

**Comment by naughtont3** [comment]
Yep, that got it.  Thanks!

To better understand, why did you move `wait_signal_callback` out from pfexec/base up to pfexec/linux? 
And when should we be using `pmix_globals.evbase` vs. `pmix_globas.evauxbase`?

**Comment by rhc54** [comment]
I moved the `wait_signal_callback` to the linux component because (a) it is a static, local function, and (b) it is the function that the event is directed to call when a SIGCHLD is recvd. Since the registration is now in the linux component, it has to be colocated there.

The only time the `evauxbase` needs to be used is when registering signal events. Unfortunately, libevent defined the event base for catching signals as a global variable, which means only _one_ event base can be used to catch signals. If you define a new event that to catch a signal and pass a different event base, they replace the global base with the new one - which means that all prior signal catching events suddenly change event base. This creates unexpected behavior that can cause you to lock up - e.g., if your original event tries to call a function that blocks in the new event base.

Unfortunately, while this fixes the problem, it also leaves us somewhat vulnerable. If the host isn't progressing that event base, or at least not very often, then we cannot respond to signals very well. Nothing we can do about it. 🤷‍♂️ 

Other than that, PMIx should always use its own internal event base.

**Comment by naughtont3** [comment]
Ok, thanks for clarifications

**Comment by rhc54** [comment]
Closing as fixed by the above patch.
