### ISSUE TITLE
`prte_stdint.h: error: conflicting types for 'intptr_t'; have 'int'`

### ISSUE THREAD

**Issue by barracuda156** [openpmix/prrte#1834]
There seems to be a conflict with GCC headers:
```
In file included from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_openmpi/openmpi-gcc13/work/openmpi-5.0.0/3rd-party/prrte/src/include/prte_config_bottom.h:265,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_openmpi/openmpi-gcc13/work/build/3rd-party/prrte/src/include/prte_config.h:800,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_openmpi/openmpi-gcc13/work/openmpi-5.0.0/3rd-party/prrte/src/util/hostfile/hostfile.c:26:
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_openmpi/openmpi-gcc13/work/openmpi-5.0.0/3rd-party/prrte/src/include/prte_stdint.h:84:20: error: conflicting types for 'intptr_t'; have 'int'
   84 | typedef signed int intptr_t;
      |                    ^~~~~~~~
In file included from /opt/local/lib/gcc13/gcc/powerpc-apple-darwin10/13.2.0/include/stdint.h:9,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_openmpi/openmpi-gcc13/work/openmpi-5.0.0/3rd-party/prrte/src/include/prte_stdint.h:40:
/opt/local/lib/gcc13/gcc/powerpc-apple-darwin10/13.2.0/include-fixed/stdint.h:93:16: note: previous declaration of 'intptr_t' with type 'intptr_t' {aka 'long int'}
   93 | typedef long   intptr_t;
      |                ^~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_openmpi/openmpi-gcc13/work/openmpi-5.0.0/3rd-party/prrte/src/include/prte_stdint.h:88:22: error: conflicting types for 'uintptr_t'; have 'unsigned int'
   88 | typedef unsigned int uintptr_t;
      |                      ^~~~~~~~~
/opt/local/lib/gcc13/gcc/powerpc-apple-darwin10/13.2.0/include-fixed/stdint.h:98:25: note: previous declaration of 'uintptr_t' with type 'uintptr_t' {aka 'long unsigned int'}
   98 | typedef unsigned long   uintptr_t;
      |                         ^~~~~~~~~
In file included from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_openmpi/openmpi-gcc13/work/openmpi-5.0.0/3rd-party/prrte/src/include/prte_config_bottom.h:265,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_openmpi/openmpi-gcc13/work/build/3rd-party/prrte/src/include/prte_config.h:800,
                 from hostfile_lex.l:26:
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_openmpi/openmpi-gcc13/work/openmpi-5.0.0/3rd-party/prrte/src/include/prte_stdint.h:84:20: error: conflicting types for 'intptr_t'; have 'int'
   84 | typedef signed int intptr_t;
      |                    ^~~~~~~~
In file included from /usr/include/machine/types.h:35,
                 from /usr/include/stdlib.h:255,
                 from /opt/local/include/LegacySupport/stdlib.h:25,
                 from hostfile_lex.c:280:
/usr/include/ppc/types.h:105:33: note: previous declaration of 'intptr_t' with type 'intptr_t' {aka 'long int'}
  105 | typedef __darwin_intptr_t       intptr_t;
      |                                 ^~~~~~~~
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_science_openmpi/openmpi-gcc13/work/openmpi-5.0.0/3rd-party/prrte/src/include/prte_stdint.h:88:22: error: conflicting types for 'uintptr_t'; have 'unsigned int'
   88 | typedef unsigned int uintptr_t;
      |                      ^~~~~~~~~
/usr/include/ppc/types.h:109:33: note: previous declaration of 'uintptr_t' with type 'uintptr_t' {aka 'long unsigned int'}
  109 | typedef unsigned long           uintptr_t;
      |                                 ^~~~~~~~~
make[5]: *** [hostfile_lex.lo] Error 1
```

**Comment by barracuda156** [comment]
This should probably check for bitness:
```
#if SIZEOF_VOID_P == SIZEOF_INT

#    ifndef HAVE_INTPTR_T
typedef signed int intptr_t;
#    endif

#    ifndef HAVE_UINTPTR_T
typedef unsigned int uintptr_t;
#    endif

#elif SIZEOF_VOID_P == SIZEOF_LONG

#    ifndef HAVE_INTPTR_T
typedef signed long intptr_t;
#    endif

#    ifndef HAVE_UINTPTR_T
typedef unsigned long uintptr_t;
#    endif
```

On 32-bit, SIZEOF_INT == SIZEOF_LONG, so two conditions are two.

**Comment by barracuda156** [comment]
A quick change to:
```
/* Pointers */

#if SIZEOF_VOID_P == SIZEOF_LONG

#    ifndef HAVE_INTPTR_T
typedef signed long intptr_t;
#    endif

#    ifndef HAVE_UINTPTR_T
typedef unsigned long uintptr_t;
#    endif

#elif SIZEOF_VOID_P == SIZEOF_LONG_LONG

#    ifndef HAVE_INTPTR_T
typedef signed long long intptr_t;
#    endif
#    ifndef HAVE_UINTPTR_T
typedef unsigned long long uintptr_t;
#    endif

#else

#    error Failed to define pointer-sized integer types

#endif
```
fixes compilation.
So yes, existing code is wrong.

**Comment by rhc54** [comment]
I'm pretty sure we no longer support 32-bit builds - @jsquyres ?

**Comment by barracuda156** [comment]
@rhc54 I am late to the party, admittedly, been too busy with other stuff, but I want to fix it for 32 bit.
(Here it is trivial to fix, but there are some spots which appeared problematic on the first run. I will need to dig into this a bit to see what is needed to have the build fixed to begin with, and then tests.)

**Comment by barracuda156** [comment]
I.e. unless someone decided to break 32-bit builds as a matter of principle (in which case I will make local fixups in Macports), and not just as a consequence of lack of extra time or hardware to test and maintain, this is desirable to have fixed in upstream – with external community contributions.

Of course, I do not imply – here or elsewhere – that others should do the work. But advice is greatly appreciated.

**Comment by jsquyres** [comment]
@rhc54 Open MPI v5.x does not support 32 bit environments.  We announced this several times in the Open MPI community, and each time we did, there was a bit of a kerfuffle with people promising to fix and continue to support 32 bit environments, but then nothing ever happened.  Hence, 32 bit environments are not supported in v5.0.0 and are not planned for future releases.  If an actual maintainer of 32 bit environments wants to come forward, we'd be happy to talk further.

If prrte doesn't support 32 bit, we should probably put in a configure check to enforce that, perhaps similar to https://github.com/open-mpi/ompi/blob/ec621900a5a6dcc226b54504715d5b4f364244ed/configure.ac#L461-L465

**Comment by rhc54** [comment]
@jsquyres IIRC, we got some rather negative responses from people who didn't like that we had hard-coded block of 32-bit support. Didn't we wind up removing that configure check (at least as an "error")?

@barracuda156 I don't oppose 32-bit support, but I think the reason people never followed thru on it is that it would be extremely hard to do. Assumption of 64-bit runs throughout the PRRTE and PMIx code base, which means any patch would be large and complex. Not sufficient to just make it compile - execution often assumes 64-bit as well, so you'd have a significant validation process to pass.

I won't rule out acceptance of such a contribution - but I would view it skeptically, for those reasons. I'd need to see some proof that the results actually work.

**Comment by jsquyres** [comment]
@rhc54 Yes, I think you're right: at least one of the times, people asked us to remove the hard-coded 32-bit check.  However, we ended up leaving it in (or putting it back in? I don't remember offhand) on the rationale that fixing 32-bit support would require patching the code, and the hard-coded check could be removed as part of that patch.  

Hence, in Open MPI v5.0.0, there's no way to avoid that check without altering `configure.ac` / `configure` (in Open MPI's `main` and `v5.0.x` branches, that is -- prior releases of Open MPI did, and still do, support 32-bit environments).

**Comment by barracuda156** [comment]
@rhc54 That was my impression last time I took part in the discussion: as I remember, upstream convinced me 32-bit builds are possible and configure does not prevent those. I left it at that, since there were other priorities at the time. Today I tried upgrade OpenMPI locally (Macports is at 4.x), at realized the code is pretty broken.
Unfortunately, it does not end on configure check and minor bugs in header macros; at the same time, for example, MPICH works on 32-bit platforms reasonably fine – it certainly not only builds itself but can be used to build multiple dependent ports.
I am not an expert in this field, so I can be wrong here, but at least from experience, 32-bit support is almost always broken or dumped due to lack of either interest or resources to maintain (which is understandable). More often that not it can be restored – I mean, that has actually been done in a number of cases with demonstrable success (`sbcl` and `kokkos` are examples in which I was involved). Of course, the question is how much effort that gonna require, and whether upstream accepts reasonable patches.

@jsquyres Yes, breaking check in configure is no real stopper at the moment, and there is no point to remove it unless the build is fixed, to begin with. I think it is reasonable to expect some test failures, and users may be warned that 32-bit platforms have no official support, but as of now, build itself is broken.

**Comment by rhc54** [comment]
@jsquyres Yeah, I'll add it to both PMIx and PRRTE since neither supports 32-bit

@barracuda156 Like I said, I won't automatically reject patches - but the changes are likely to be significant and widespread, which means there has to be equally significant evidence that they work and don't cause problems for 64-bit operations.

Reading the several issues you filed, it appears you are trying to make this work on PowerPC Macs running SnowLeopard?? Outside of a museum, it is hard to believe that represents a real world application - certainly not a significant user base. I'd recommend anyone actually in that situation just stick to older versions of OMPI and let this go. Can't be worth the effort it would require to backport these codes.

**Comment by rhc54** [comment]
I'm pretty sure PRRTE has never supported 32-bit environments, though it is somewhat derived from the old ORTE, which used to do so. If you want to pursue this, feel free to include a fix for this in your patch. Meantime, I'm going to close this as "won't be fixed", and will add the configure check for later releases.

**Comment by barracuda156** [comment]
@rhc54 What would be a sufficient criteria to consider it working (assuming build itself is fixed)?

Of course, it must not introduce any undesired effects for other platforms, this goes without saying. But testing 64-bit on platforms of your interest is a routine procedure before merging any PR anyway. There is nothing special in this sense here.

P. S. `ppc32` is presently supported on FreeBSD, OpenBSD, several variants of Linux and likely a few other systems. While I am using Darwin at the moment, the issue is nothing macOS-specific, at least so far. Most of 32-bit-specific problems will just as well apply to `i386`, `arm` and `mips`.

**Comment by rhc54** [comment]
I realize that various people have a 32-bit repo - I also realize that those repos are virtually unused. It's more of a policy issue for those organizations. We've had discussions with them in the past (since we are forcing breakage of their policy), and the problem really is that they don't have a mechanism for "sunsetting" support - and so they are stuck posting releases that they know are largely unused. Someday, they will figure out a way to resolve the situation - but we aren't in a similar position.

I honestly don't have a specific set of acceptance criteria for this situation as it hasn't come up before. Just building clearly isn't sufficient. You would have to change actual standardized values (e.g., bitmasks, defined return values) that rely on 64-bits. PMIx has a cross-version requirement, so you'd have to think about how interactions (for example) between a 64-bit server and 32-bit client would work. Etc.

Like I said, it requires more than just patches to make something build. Would take considerable thought on how you have to modify the system and what those modifications mean to the overall PMIx community.

**Comment by jsquyres** [comment]
@barracuda156 At least some level of automated CI testing would likely be required.  Like @rhc54 said, building isn't sufficient -- we need to know that it's actually working.

Open MPI, PMIx, and PRRTE *used* to be 32-bit clean -- a long time ago.  But we stopped caring about 32 bit quite a long time ago, and really have not tested since.  So it's true that we don't *know* that it's not working, but by the same token, no one else has said "Yes, I am using 32 bit for actual, real-world HPC", either.  It's unfortunately just a question of resources -- we do not have the resources to keep validating 32-bit platforms that no one is using for the use cases that we need to support (i.e., newer, more modern hardware that runs the world's most advanced HPC / AI / ML computing scenarios).  ☹️ 

Do you think you could supply some CI testing on PRs and merges in 32-bit environments for Open MPI, PRRTE, and PMIx, perchance?

**Comment by jsquyres** [comment]
@barracuda156 Actually, I missed @rhc54's comment:

> You would have to change actual standardized values (e.g., bitmasks, defined return values) that rely on 64-bits. PMIx has a cross-version requirement, so you'd have to think about how interactions (for example) between a 64-bit server and 32-bit client would work. Etc.

That would seem to be a large problem: the PMIx standard itself *requires* 64 bit values.  This is not your standard set of "make sure you're using the right-sized types and not being sloppy about casting and converting between types" 32/64 clean issues.

**Comment by barracuda156** [comment]
> Do you think you could supply some CI testing on PRs and merges in 32-bit environments for Open MPI, PRRTE, and PMIx, perchance?

@jsquyres It is certainly possible to have CI set for `i368` (32-bit Linux) and AFAIK even `ppc` (trickier, via `Qemu`). I will find links to actual GitHub actions being set for this purpose. It is not something I can write myself, but I have seen recent real-life examples.

**Comment by barracuda156** [comment]
> That would seem to be a large problem: the PMIx standard itself _requires_ 64 bit values. This is not your standard set of "make sure you're using the right-sized types and not being sloppy about casting and converting between types" 32/64 clean issues.

@jsquyres To be clear, what is implied by this specifically? There is no problem to support 64-bit (and with minor caveats 128-bit) values on 32-bit platforms.
What differs are that some types which do not specify bitness will differ in this regard (but they can be specified correctly, and that is, provisionally, an improvement to the codebase) and that we do not have hardware support for 64-bit atomics, for example (it is supported via software emulation though).

**Comment by jsquyres** [comment]
Regarding CI: ok, great.  We'd need someone to set that up.

Regarding the 64 bit values: understood.  Someone will need to both identify these places in the code, and then supply a patch to make these must-be-64-bit-values work in a 32 bit environment.  And probably also supply test cases to ensure that they continue working in both 32 and 64 bit environments (since all current testing is exclusively in 64 bit environments).  I think the point here is that this might be a bigger effort than one might imagine; it's not just a simple "make sure your using the right-sized types" kind of 32/64 cleanliness issue.

Just to clarify: are you motivated for this by real 32-bit HPC use cases?  Filling out the compatibility matrix?  ...something else?

**Comment by rhc54** [comment]
First, let's be clear that I think this issue was filed for PRRTE, which (unlike PMIx) is not governed by a Standard. So there isn't anything specifically in PRRTE itself that mandates 64-bit.

The problem with converting PRRTE to support 32-bit lies instead in its interface to PMIx. Remember, PRRTE is the PMIx Reference RTE - it is built entirely on top of PMIx. Thus, unless the underlying PMIx has been built 32-bit, there is no point in worrying about PRRTE supporting it.

The bigger question, therefore, is: can you make PMIx 32-bit? A brief review of that code indicates "not without a great deal of work and thought". At the least, we would have to modify the client/server handshake to include a marker indicating "I am 32-bit" vs "I am 64-bit" so that the underlying communication system (PMIx "bfrops" framework) can select the proper component to support it. Someone would then have to write a 32bit-to-64bit component, which is probably not trivial.

You'd also need to make changes throughout the library to deal with 64-bit values while in 32-bit mode. I suspect you'd have to disable the shared memory subsystem, or come up with some way of handling it when the client and server are in different build types.

All told, it made my head hurt to even consider it in a review. Minus some documented real world demand for 32-bit systems, I'm inclined to simply nix this line of inquiry. Hence, I think @jsquyres last question is the critical one: are their real 32-bit HPC use cases we don't know about? If so, we'd need to understand what they are, and why moving to 64-bit isn't a feasible answer.

Note that even if you can convince me to make PMIx and PRRTE 32-bit compliant, you'd still have to convince the OMPI community (which is separate from this one) to also do it for the MPI library. So you have _three_ hills to climb...

**Comment by barracuda156** [comment]
@jsquyres @rhc54 Regarding motivation behind: I bumped into these errors when trying to upgrade OpenMPI, as PRRTE and PMIx are used in it as required components. I did not consider any standalone usage and I am not aware of associated complications (possibly, OpenMPI uses these for a subset of possible applications).
I do not think we have separate ports for PRRTE and PMIx in Macports, so the only concern from my side is OpenMPI-related.

Macports uses MPICH and OpenMPI interchangeably (i.e. normally a user may choose desired implementation), but select ports do require OpenMPI specifically or for some reason are broken with MPICH (reverse cases also are there). In particular, one or two ports which I added and maintain need OpenMPI.

My impression from the last discussion with upstream was that while 32-bit support is totally untested, perhaps for years, there was no inherent reasons for it to be broken and no one tried to break in on purpose. With that in mind, I thought that we could fix some number of bugs which went unnoticed (due to no testing) and possibly add macOS-specific fixes (whether in upstream or locally in Macports), which may be needed for older SDKs. Most of the latter are known.
I expected to encounter some endianness-related issues, since, unfortunately, modern Big-endian hardware is scarce and expensive (and old one is getting scarce), and fixing those issues would have benefited the codebase – BE is not restricted to archaic MacOS.

In fact I suspect OpenMPI 4.x was already partly broken – and that issues I hoped to fix along in the process in OpenMPI 5 (instead of spending effort on already outdated version, fixes for which will unlikely be merged to upstream anyway).

At the moment I have no idea if that is practically feasible. If I can fix the build of OpenMPI with moderate efforts, I will be tempted to try making sure tests pass. If the build itself will turn out to be hopelessly broken, rewriting all this from scratch is not a realistic option, of course.

**Comment by rhc54** [comment]
OMPI v5 is a bit of a departure from prior releases in that it is directly tied to PMIx, which is used throughout the code base. You can build and use OMPI without PRRTE (you won't have `mpirun`, so you need some other way to start the processes) - you cannot do it without PMIx.

You might be able to hack the version of PMIx embedded in OMPI v5 and perhaps get something that will work solely on the Mac. Of course, that code will no longer be supported under such conditions - there is no way I can deal with downstream modified code. So any problems encountered would fall on you to resolve. Unfortunately, since you'd undoubtedly be distributing only the one code base (i.e., one that supported both 32 and 64 bits), and that would be the modified one, it means you'd have to take on support for all Mac installations, not just 32-bit ones.

If you need `mpirun` to launch processes, then you'll have to modify the embedded PRRTE as well (with the same implication for supporting it). And as already noted, you'll have to update the MPI layer as well (support issue is up to them).

Only you can determine is whether or not it's worth all that to support the very few people out there with such old systems. Based on what I've seen so far, it's rather doubtful you could upstream the changes - we'd need you to meet all the cross-version requirements and Standard compliance, which you could ignore for a Mac-only distribution.

**Comment by barracuda156** [comment]
> Unfortunately, since you'd undoubtedly be distributing only the one code base

@rhc54 No, it is neither required by Macports policies nor needed technically. Of course, I cannot make a unilateral decision – I am not a maintainer of OpenMPI port, but it is a common practice to apply any complex and potentially breaking patches only for specific arch or macOS version. Even without you saying this, I would prefer having such patches used conditionally. And of course, we would not want to introduce any complications for support of newer 64-bit systems.

Macports is very flexible in this regard: there is no one-size-fits-all. The real concern is that if needed patches are ridiculously huge and upstream is unwilling to merge those, maintaining those will be a practical problem: no one will want to carry thousands-LOC-patches indefinitely (myself included). As long as patches are reasonable and someone is there to maintain those, it is perfectly doable.

I appreciate that you cared to explain all this. Let me see if I can get OpenMPI itself built first (I think PMIx and PRRTE did build already, and fixes were tiny and trivial – this does not mean of course that they gonna work correctly); initially I got stuck at a broken Opal. If the build gets fixed, I will try OpenMPI tests; once/if that works, I can return to PMIx and PRRTE specifically. If the endeavor will seem too demanding or hopeless prior to that point, well, I guess just leaving it broken will not kill anyone :)
