### ISSUE TITLE
Memory leak in persistent DVM prted's

### ISSUE THREAD

**Issue by jsquyres** [openpmix/prrte#373]
I have the following setup:

1. `salloc -n 2` (get 2 SLURM nodes, and then be inside the job)
2. `prted --daemonize`
3. while forever; do prun hostname; done

This will run for nearly 32,000 times.  During these runs:

1. By watching `top`, you can see the `prted` local to `prun` obviously growing in size.
1. By watching `top`, you can see the `prted`s on the worker nodes growing in size, but significantly slower than the `prted` on the `prun` node.

**Comment by rhc54** [comment]
@ggouaillardet Would you have time to look at this?

**Comment by ggouaillardet** [comment]
I am pretty busy these days, but Monday is a national holiday :-)
I will take a crack at it

**Comment by jjhursey** [comment]
@jsquyres the 32k jobs limit part of this issue was resolved with PR #374 . I was able to run 100K jobs against the same `prte` daemon with that patch.

The memory leak is still there, but maybe a bit smaller now. It looks like about 6KB is leaked per job during the run. Valgrind on the `prte` daemon turned up a few places to look. We will keep this open until we can work through them.

**Comment by rhc54** [comment]
Critical that we resolve this and keep it down for DVM operations - not important for OMPI usage.

**Comment by rhc54** [comment]
@awlauria When you looked at memory leaks, did you check the `prted` as well? Or just `prte`?

**Comment by rhc54** [comment]
This appears to have been resolved.
