### ISSUE TITLE
prterun --bind-to core command with more slots per node than cores per node fails

### ISSUE THREAD

**Issue by drwootton** [openpmix/prrte#673]
### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

Master branch
### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

Master branch
### Please describe the system on which you are running

-    Operating system/version:
    RHEL 7.7

-    Computer hardware:

4 Power 8 nodes, 2 sockets each with 10 cores (20 total) and 8 hwthreads per core (160 total)

-    Network type:

Hostfile specifies 4 nodes, each with slots=32 keyword

### Details of the problem
I ran the command 
```
prterun -n 32 --hostfile hostfile32 --map-by core --bind-to core taskinfo
```
where the hostfile list 4 nodes, each with slots=32, and each node actually has 20 cores

This failed with messages
```
A request was made to bind to that would result in binding more
processes than cpus on a resource:

   Bind to:     CORE
   Node:        c712f6n01
   #processes:  1
   #cpus:       1

You can override this protection by adding the "overload-allowed"
option to your binding directive.
```
Maybe this is incorrect usage since I specify more slots than existing cores, but I thought that the additional 12 tasks would just be allocated to the second node in the hostfile.

If I changed **--bind-to core** to **--bind-to core:overload-allowed** the command ran successfully.

If I changed **--map-by core --bind-to core** to **--map-by-core:HWTCPUS --bind-to core** that command also worked.

I added the **:REPORT** keyword to the --bind-to option. 

When I used the :overload-allowed keyword, the binding report showed me 32 tasks mapped to cores 0..19, as expected.

When I used the **:HWTCPUS** keyword, without using the :overload-allowed keyword, the binding report showed me each task assigned to the next sequential block of 8 hwthreads, where that block corresponded to the next sequential core 0..19. It seems like prterun is just allocating the same resource, but by a different name.

**Comment by rhc54** [comment]
This appears to be working now - can you please recheck?

**Comment by drwootton** [comment]
These tests are still failing identically today after I cloned new repositories for PMIx and PRRTE. I also made sure that I was on the master branch for both, and ran git pull in both just to be sure my code was latest code.

**Comment by rhc54** [comment]
Still working for me, but that may be an oddity of this Docker configuration. I'll try on something else.

**Comment by rhc54** [comment]
I think I see the difference here - I had overlooked the fact that you specified more slots than cores in your hostfile. In fact, `prterun` is acting exactly as it should. You told it that it could map 32 tasks on each node - this will be respected regardless of the number of cores as the two values (slots vs cores) are not in any way connected to each other. So `prte` maps 32 procs on the first node and then tries to honor your request to bind each proc to a core - which cannot be successfully completed unless you either (a) authorize overload or (b) switch to considering HTs as independent cpus.

If you map-by core, we will assign the procs by core. However, if we consider HTs as independent cpus, each of those cores is considered to have 8 cpus under it. We will therefore allow you to bind up to 8 procs to that core as they will be sharing 8 cpus. On the other hand, if we consider cores to be the independent cpus, then a core only has one cpu in it - and so you can only bind one proc to each core without overloading it.

HTH - I think this can be closed, or at least converted to a documentation issue.

**Comment by jjhursey** [comment]
Ralph and I brainstormed this (or something related, but I'll put it here) a bit and concluded the following:
 * `--map-by core --bind-to hwthread` is an error since the lowest allocatable unit is 'core' by default. So you cannot bind below a core.
   * We _could_ infur `--map-by core:HWTCPUS` since `--bind-to hwthread` but that will make the code more complex for what is currently a bit of an edge case. We would prefer the users be explicit with the `:HWTCPUS` qualifier.
 * `--map-by core:HWTCPUS --bind-to hwthread` is correct since the user is saying the lowest allocatable unit is 'hwthread'.
   * The behavior should be logically the same mapping/binding as if the user tried `--map-by package --bind-to core` - just at one level deeper in the hardware topology.

**Comment by drwootton** [comment]
I think that's reasonable. I think not adding special cases here is reasonable, and that doing so might make things more confusing since there would be implicit behavior here where similar cases might not have the same implicit behavior.

My problems, as I was learning what the --map-by, --bind-to and --rank-by options did were first that I didn't fully understand the interactions between the three options and the order that the options were applied, and then the interactions with the hostfile slots specs, and second, I couldn't find any description of some of the default behaviors, particularly --map-by.

**Comment by rhc54** [comment]
Some experimentation resulted in this being modified a tad. Turns out we really cannot `bind-to hwthread` if we aren't treating HWTs as independent CPUs. You wind up with some rather unexpected results that look exactly the same as if you had specified `--map-by :hwthreads`.

So here is what it finally looks like:
```text
$ prterun --map-by :DISPLAY:DONOTLAUNCH --bind-to hwthread
--------------------------------------------------------------------------
We cannot bind to hardware threads if we are not treating hardware
threads as independent CPUs since the lowest allocatable unit is
"core" by default. In order to bind to hardware threads, you must
therefore specify that we treat hardware threads as independent CPUs
by adding the "HWTCPUS" modifier to the "--map-by" directive.

The combination "--map-by core:hwtcpus --bind-to hwthread" or
"--map-by :hwtcpus --bind-to hwthread" will result in one process
being placed on each core, with the process bound to the first
hardware thread in that core.

In contrast, a case such as "--map-by package:hwtcpus --bind-to hwthread"
would result in each process being bound to successive hardware threads
on each package.
--------------------------------------------------------------------------
```
```text
$ prterun --map-by :DISPLAY:DONOTLAUNCH:hwtcpus --bind-to hwthread:REPORT
Data for node: Ralphs-iMac-2	Num slots: 10	Max slots: 0	Num procs: 3
        Process jobid: prterun-Ralphs-iMac-2-75138@1 App: 0 Process rank: 0 Bound: package[0][hwt:0]
        Process jobid: prterun-Ralphs-iMac-2-75138@1 App: 0 Process rank: 1 Bound: package[0][hwt:2]
        Process jobid: prterun-Ralphs-iMac-2-75138@1 App: 0 Process rank: 2 Bound: package[0][hwt:4]
```
```
$ prterun --bind-to hwthread:REPORT
--------------------------------------------------------------------------
We cannot bind to hardware threads if we are not treating hardware
threads as independent CPUs since the lowest allocatable unit is
"core" by default. In order to bind to hardware threads, you must
therefore specify that we treat hardware threads as independent CPUs
by adding the "HWTCPUS" modifier to the "--map-by" directive.

The combination "--map-by core:hwtcpus --bind-to hwthread" or
"--map-by :hwtcpus --bind-to hwthread" will result in one process
being placed on each core, with the process bound to the first
hardware thread in that core.

In contrast, a case such as "--map-by package:hwtcpus --bind-to hwthread"
would result in each process being bound to successive hardware threads
on each package.
--------------------------------------------------------------------------
```
```text
$ prterun --map-by package:DISPLAY:DONOTLAUNCH:hwtcpus --bind-to hwthread:REPORT
Data for node: Ralphs-iMac-2	Num slots: 10	Max slots: 0	Num procs: 3
        Process jobid: prterun-Ralphs-iMac-2-75178@1 App: 0 Process rank: 0 Bound: package[0][hwt:0]
        Process jobid: prterun-Ralphs-iMac-2-75178@1 App: 0 Process rank: 1 Bound: package[0][hwt:1]
        Process jobid: prterun-Ralphs-iMac-2-75178@1 App: 0 Process rank: 2 Bound: package[0][hwt:2]
```

**Comment by rhc54** [comment]
Just for grins:
```text
$ prterun --map-by package:pe=2:DISPLAY:DONOTLAUNCH:hwtcpus --bind-to hwthread:REPORT
Data for node: Ralphs-iMac-2	Num slots: 10	Max slots: 0	Num procs: 3
        Process jobid: prterun-Ralphs-iMac-2-75227@1 App: 0 Process rank: 0 Bound: package[0][hwt:0-1]
        Process jobid: prterun-Ralphs-iMac-2-75227@1 App: 0 Process rank: 1 Bound: package[0][hwt:2-3]
        Process jobid: prterun-Ralphs-iMac-2-75227@1 App: 0 Process rank: 2 Bound: package[0][hwt:4-5]
```

**Comment by jjhursey** [comment]
This is a good one for the documentation. The difference between "overloaded" and "oversubscribed" can be teased out here with this example. I'll work on that and post it here.

One curiosity that I found while writing this is that the examples below work without throwing the overload warning even though the cores are overloaded:
```
prterun --np 34 --hostfile hostfile-32.txt --map-by core:HWTCPUS --bind-to core:REPORT hostname
prterun --np 34 --hostfile hostfile-32.txt --map-by package:HWTCPUS --bind-to package:REPORT hostname
```

I expected the same error as if I used either of the following without the `:HWTCPUS` qualifier.
```
prterun --np 34 --hostfile hostfile-32.txt --map-by core --bind-to core:REPORT hostname
prterun --np 34 --hostfile hostfile-32.txt --map-by package --bind-to package:REPORT hostname
```

**Comment by jjhursey** [comment]
What do you think about the following for the man page? If you like it then I can add it to the `prte-map.1` manpage in PR #773

------

## Difference between overloading and oversubscription

This section explores the difference between these two options.

 - `--bind-to <object>:overload-allowed` allows for binding more than one processes to this object.
 - `--map-by :OVERSUBSCRIBE` allow more processes on a node than processing elements

For the following examples consider a node with:
 - Two processor packages,
 - Four cores per package, and
 - Eight hardware threads per core.

And the following hostfile:

```
$ cat myhostfile
node01 slots=32
node02 slots=32
```

The "slots" tells PRTE that it can place up to 32 processes before oversubscribing the node.

If we run the following:
```
prterun --np 34 --hostfile myhostfile --map-by core --bind-to core hostname
```

It will return an error at the binding time indicating an overloading scenario.

The mapping mechanism assigns 32 processes to `node01` matching the "slots" specification in the hostfile. The binding mechanism will bind the first 20 processes to unique cores leaving it with 12 processes that it cannot bind without overloading one of the cores (putting more than one process on the core).

Using the `overload-allowed` qualifier to the `--bind-to core` option tells PRTE that it may assign more than one process to a core.

If we run the following:
```
prterun --np 34 --hostfile myhostfile --map-by core --bind-to core:overload-allowed hostname
```

This will run correctly placing 32 processes on `node01`, and 2 processes on `node02`. On `node01` two processes are bound to cores 0-11 accounting for the overloading of those cores.

Alternatively, we could use hardware threads to give binding a lower level processing unit to bind to without overloading.

If we run the following:
```
prterun --np 34 --hostfile myhostfile --map-by core:HWTCPUS --bind-to hwthread hostname
```

This will run correctly placing 32 processes on `node01`, and 2 processes on `node02`. On `node01` two processes are mapped to cores 0-11 but bound to different hardware threads on those cores (the logical first and second hardware thread) thus no hardware threads are overloaded at binding time.

In both of the examples above the node is not oversubscribed at mapping time because the hostfile set the oversubscription limit to "slots=32" for each node. It is only after we exceed that limit that PRTE will throw an oversubscription error.

Consider next if we ran the following:
```
prterun --np 66 --hostfile myhostfile --map-by core:HWTCPUS --bind-to hwthread hostname
```

This will return an error at mapping time indicating an oversubscription scenario. The mapping mechanism will assign all of the available slots (64 across 2 nodes) and be left two processes to map. The only way to map those processes is to exceed the number of available slots putting the job into an oversubscription scenario.

You can force PRTE to oversubscribe the nodes by using the `:OVERSUBSCRIBE` modifier to the `--map-by` option as seen in the example below:
```
prterun --np 66 --hostfile myhostfile --map-by core:HWTCPUS:OVERSUBSCRIBE --bind-to hwthread hostname
```

This will run correctly placing 34 processes on `node01` and 32 on `node02`. Each process is bound to a unique hardware thread.

**Comment by rhc54** [comment]
> What do you think about the following for the man page? If you like it then I can add it to the `prte-map.1` manpage in PR #773

Sounds like a good idea. Other than the math problem cited below, I think it is fine.

> ## Difference between overloading and oversubscription
> 
> This section explores the difference between these two options.
> 
>     * `--bind-to <object>:overload-allowed` allows for binding more than one processes to this object.
> 
>     * `--map-by :OVERSUBSCRIBE` allow more processes on a node than processing elements
> 
> 
> For the following examples consider a node with:
> 
>     * Two processor packages,
> 
>     * Four cores per package, and
> 
>     * Eight hardware threads per core.
> 
> 
> And the following hostfile:
> 
> ```
> $ cat myhostfile
> node01 slots=32
> node02 slots=32
> ```
> 
> The "slots" tells PRTE that it can place up to 32 processes before oversubscribing the node.
> 
> If we run the following:
> 
> ```
> prterun --np 34 --hostfile myhostfile --map-by core --bind-to core hostname
> ```
> 
> It will return an error at the binding time indicating an overloading scenario.
> 
> The mapping mechanism assigns 32 processes to `node01` matching the "slots" specification in the hostfile. The binding mechanism will bind the first 20 processes to unique cores leaving it with 12 processes that it cannot bind without overloading one of the cores (putting more than one process on the core).

I think the math here isn't correct - you have two packages each with four cores, which only totals 8 cores on each node for a total of 16 cores in the system.

> 
> Using the `overload-allowed` qualifier to the `--bind-to core` option tells PRTE that it may assign more than one process to a core.
> 
> If we run the following:
> 
> ```
> prterun --np 34 --hostfile myhostfile --map-by core --bind-to core:overload-allowed hostname
> ```
> 
> This will run correctly placing 32 processes on `node01`, and 2 processes on `node02`. On `node01` two processes are bound to cores 0-11 accounting for the overloading of those cores.

There are only 8 cores on node01

> 
> Alternatively, we could use hardware threads to give binding a lower level processing unit to bind to without overloading.
> 
> If we run the following:
> 
> ```
> prterun --np 34 --hostfile myhostfile --map-by core:HWTCPUS --bind-to hwthread hostname
> ```
> 
> This will run correctly placing 32 processes on `node01`, and 2 processes on `node02`. On `node01` two processes are mapped to cores 0-11 but bound to different hardware threads on those cores (the logical first and second hardware thread) thus no hardware threads are overloaded at binding time.
> 
> In both of the examples above the node is not oversubscribed at mapping time because the hostfile set the oversubscription limit to "slots=32" for each node. It is only after we exceed that limit that PRTE will throw an oversubscription error.
> 
> Consider next if we ran the following:
> 
> ```
> prterun --np 66 --hostfile myhostfile --map-by core:HWTCPUS --bind-to hwthread hostname
> ```
> 
> This will return an error at mapping time indicating an oversubscription scenario. The mapping mechanism will assign all of the available slots (64 across 2 nodes) and be left two processes to map. The only way to map those processes is to exceed the number of available slots putting the job into an oversubscription scenario.
> 
> You can force PRTE to oversubscribe the nodes by using the `:OVERSUBSCRIBE` modifier to the `--map-by` option as seen in the example below:
> 
> ```
> prterun --np 66 --hostfile myhostfile --map-by core:HWTCPUS:OVERSUBSCRIBE --bind-to hwthread hostname
> ```
> 
> This will run correctly placing 34 processes on `node01` and 32 on `node02`. Each process is bound to a unique hardware thread.

**Comment by jjhursey** [comment]
Good catch. I was using a P8 box for testing. I'll change the node description to match:
```
* Two processor packages,
* Ten cores per package, and
* Eight hardware threads per core.
```
Thanks!

**Comment by jjhursey** [comment]
I fixed the documentation in PR #773 

Before I can close this issue I'm curious if we have a feel for the bug/behavior I mentioned in [this comment](https://github.com/openpmix/prrte/issues/673#issuecomment-784564995).

**Comment by rhc54** [comment]
This is a common misunderstanding - people often think in terms of cores instead of CPUs

> prterun --np 34 --hostfile hostfile-32.txt --map-by core:HWTCPUS --bind-to core:REPORT hostname
> prterun --np 34 --hostfile hostfile-32.txt --map-by package:HWTCPUS --bind-to package:REPORT hostname

As you have declared HWTs to be CPUs, your result is actually not overloaded since you are binding above the CPU level, and there are still more CPUs than procs underneath that level. You have eight HTs/core, but only wound up binding a max of 2 procs/core - not overloaded. In the package case, you have a max of 17 procs/package, but 80 CPUs in the package - not overloaded.

The following case is different:
> prterun --np 34 --hostfile hostfile-32.txt --map-by core --bind-to core:REPORT hostname
> prterun --np 34 --hostfile hostfile-32.txt --map-by package --bind-to package:REPORT hostname

Here we default to cores as CPUs and we wind up with more procs than CPUs (cores) in at least one location because you declared 32 slots/node. The first node gets 32 procs on it, but has only 20 CPUs - some of the cores are overloaded when binding to core. Binding to package has the same result as you have 17 procs/package, but only 10 CPUs/package.

If you had said `--bind-to none`, then you would _not_ have been overloaded as we wouldn't have bound the procs - even though `--bind-to package` is a pretty loose binding, it is still a binding.

**Comment by jjhursey** [comment]
Ok I think I follow now. Check my logic below for the `--map-by package --bind-to package:REPORT` case.

If it looks good then I'll add it to the documentation.

------

Consider a node wtih `2 packages of 10 cores each with 8 hwthreads` (same as before) and the hostfile:
```
$ cat myhostfile
node01 slots=22
node02 slots=22
```

The lowest level CPUs are 'cores' and we have 20 total (10 per package).

If I run:
```
prterun --np 20 --hostfile myhostfile--map-by package --bind-to package:REPORT hostname
```

Then 10 processes are mapped to each package, and bound at the package level. This is not overloading since we have 10 CPUs (cores) available in the package at the hardware level.

However, if I run:
```
prterun --np 21 --hostfile myhostfile --map-by package --bind-to package:REPORT hostname
```

Then 11 processes are mapped to the first package and 10 to the second package. At binding time we have an overloading scenario because there are only 10 CPUs (cores) available in the package at the hardware level. So the first package is overloaded.

Similarly, if we consider hardware threads.

Consider a node wtih `2 packages of 10 cores each with 8 hwthreads` (same as before) and the hostfile:
```
$ cat myhostfile
node01 slots=165
node02 slots=165
```

The lowest level CPUs are 'hwthreads' (because we are going to use the `:HWTCPUS` qualifier) and we have 160 total (80 per package).

If I re-run (from above) and add the `:HWTCPUS` qualifier:
```
prterun --np 21 --hostfile myhostfile --map-by package:HWTCPUS --bind-to package:REPORT hostname
```

Without the `:HWTCPUS` qualifier this would be overloading (as we saw previously). The mapper places 11 processes on the first package and 10 to the second package. The processes are still bound to the package level. However, with the `:HWTCPUS` qualifier, it is not overloading since we have 80 CPUs (hwthreads) available in the package at the hardware level.

Alternatively, if I run:
```
prterun --np 161 --hostfile myhostfile --map-by package:HWTCPUS --bind-to package:REPORT hostname
```

Then 81 processes are mapped to the first package and 80 to the second package. At binding time we have an overloading scenario because there are only 80 CPUs (hwthreads) available in the package at the hardware level. So the first package is overloaded.

**Comment by rhc54** [comment]
Yeah, that is correct. You might want to add a sentence or three emphasizing that "overload" is defined as "more processes than CPUs", and that CPUs are not always correlated to "cores". I think that is the point people tend to forget the most - everyone is so used to thinking of "slots = cores" and "cores = cpus" that they forget such equivalences were simply convention on older machines...and no longer applicable on today's modern architectures.

**Comment by jjhursey** [comment]
I can update the doc. I clarified the definition of `overload-allowed`
```
- `--bind-to <object>:overload-allowed` allows for binding more than one process in relation to a CPU.
```

Add added this text
```
The important thing to remember with _oversubscribing_ is that it can be
defined separately from the actual number of CPUs on a node. This allows the
mapper to place more or fewer processes per node than CPUs. By default, PRTE
uses cores to determine slots in the absence of such information provided in
the hostfile or by the resource manager (except in the case of the `--host`
as described in the "Specifying Host Nodes" section).

The important thing to remember with _overloading_ is that it is defined as
binding more processes than CPUs. By default, PRTE uses cores as a means of
counting the number of CPUs. However, the user can adjust this. For example
when using the `:HWTCPUS` qualifier to the `--map-by` option PRTE will use
hardware threads as a means of counting the number of CPUs.
```

**Comment by jjhursey** [comment]
I pushed that clarification above to #773 - we can close now. Thanks for helping me sort through that. I dare say I think I understand it now.
