### ISSUE TITLE
--help listed parameters 'Deprecated' or have no effect needs to be documented/undeprecated/fixed

### ISSUE THREAD

**Issue by abouteiller** [openpmix/prrte#709]
## Background information

A large number of prte/mpiexec options report as 'deprecated', however, they are not reported as such in `mpiexec --help`

Other parameters appear to not work/have no effect

We need to decide for each param if 
1. the parameter should be 'undeprecated'
2. the parameter should be marked as 'deprecated' in the output of `mpiexec --help` and in the `man mpiexec`/`man prte`/`man prun`, as applicable

These will be referred to a as 'option 1' and 'option 2' in the list of options below

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

Open MPI master

```shell
$ git show
d36977c9 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #8296 from rhc54/topic/pmixv4 

$ git submodule
 2e3df8ee02bd21e20a3675f580eccc38cbe014a4 3rd-party/openpmix (v4.0.0rc1)
 f2b3d3495b72540a97c85311c289c4126657e738 3rd-party/prrte (dev-30794-gf2b3d349)
```

### Please describe the system on which you are running

* Operating system/version: CentOS7
* Computer hardware: x86_64
* Network type: mlx5

-----------------------------

### Using the option works, but issues a 'DEPRECATED' warning at runtime

- [x] display-allocation (recommend undeprecating: option 1)
- [x] display-map (1)
- [x] tag-output (1)
- [x] timestamp-output (1)
- [x] xml (1)
- [x] report-bindings (recommend deprecating: option 2, add `display-binding`)

### Using the option has no effect

- [x] report-pid (2)
- [x] -d (--debug does work though) (fix: map to --debug)
- [x] debug-devel (2, map to --debug)
- [ ] debug-daemon-file (no file produced anywhere, if it works, it needs more explanation of how to use)
- [ ] output-proctable (no output, 2 if not useful anymore?)
- [x] test-suicide (2)
- [x] output-directory (1: should be fixed, this is -very- useful)
- [ ] xterm (maybe it's something on my setup, needs confirmation)
- [x] display-devel-allocation (2, map to --display-allocation)
- [x] display-diffable-map (2)
- [x] display-topo (maybe it's something that works only when building with lstopo? needs confirmation, 2 if not useful anymore)
- [ ] default-hostfile (no effect, 2?)

### Unconclusive (not sure if it works)

- [x] merge-stderr-to-stdout (unsure if works)
- [x] do-not-resolve (appears to do nothing, needs documentation)
- [x] index-argv-by-rank (appears to do nothing, needs documentation)

**Comment by jjhursey** [comment]
For reference (if it helps)
 * https://github.com/open-mpi/ompi/wiki/Webex-affinity-discussions-2019-09

**Comment by jjhursey** [comment]
Per teleconf Jan. 14, 2021 (please correct me where my notes are inaccurate):
 * All of the options (unless otherwise noted) should be in the core `prte` personality to be generally available
 * For debug/verbosity options, this would be quite challenging to implement on a per-job basis since the output is not generally associated with a specific job. Instead, these options should be globally set in the HNP process for all jobs.
 * Create a `--output A[,B,C]` option where the arguments to `--output` is a comma-separated list of options that control the output generated.
   * `tag` replaces the old `--tag-output`
   * `timestamp` replaces the old `--timestamp-output`
   * `xml` replaces the old `--xml`
   * `merge-stderr-to-stdout` replaces the old `--merge-stderr-to-stdout`
   * `dir:DIRNAME` replaces `--output-directory DIRNAME` (we may keep an alias for `--output-directory` if needed)
 * Create a `--display A[,B,C]` (or `--report` if folks like that better) where the arguments to `--display` is a comma-separated list of options for displaying information about the allocation and job.
   * `allocation` replaces `--display-allocation`.  Keep `--map-by :DISPLAYALLOC`
   * `map`/`mapping` replaces `--display-map`. Keep `--map-by :DISPLAY`
   * `bind`/`binding` replaces `--report-bindings`/`--display-bindings`. Keep `--bind-to :REPORT`
   * `proctable` replaces `output-proctable`.
   * `allocation-devel` replaces `display-devel-allocation` (need to check if this distinction is still meaningful). Is this `--map-by :DISPLAYDEVEL`?
   * `map-diffable` replaces `--display-diffable-map`.  Keep `--map-by :DISPLAYDIFF`
   * `topo` replaces `--display-topo`.  Keep `--map-by :DISPLAYTOPO`
 * `--report-pid` remove CLI option, settable via internal MCA
   * It prints the pid of the launcher process
 * `--debug` (map to `-d`) we should probably keep, but make it ompi only?
   * It relaunches the launcher under the specified debugger.
 * `--debug-devel` remove CLI option, settable via internal MCA
   * Unclear how much this enables given that most output comes from MCA components. Need to evaluate this option.
 * `--debug-daemon-file` remove CLI option, settable via internal MCA
   * It is very useful when debugging daemons across multiple nodes - esp. those that have daemonized and don't send stdio to the HNP.
 * `--xterm` deprecate/remove.
   * Unclear if anyone uses this anymore.
 * `--test-suicide` remove CLI option, settable via internal MCA
   * Useful when checking if everything cleans up properly when something fails. Developer only option.
 * `--default-hostfile` should be a CLI option to `prterun` and `prte`, but not `prun`
   * This specifies the total set of machines available which is useful for unmanaged environments. The `--hostfile/--host` options can choose a subset from this larger set. This option is meant to be global in nature, and set by an admin or whoever controls the job launch in the allocation.
 * `--do-not-resolve` remove CLI option, settable via internal MCA.
   * Developer only option useful when testing the mapper. Prevents the hostname resolution since the hostnames might not be valid, and are only there to test the mapper. Users should not be using this.
 * `--index-argv-by-rank` Remove CLI option, settable via internal MCA.
   * Appends the rank to argv. Each rank interprets the CLI differently based on this option before MPI_Init.

**Comment by jjhursey** [comment]
Per teleconf Jan. 21, 2021 (please correct me where my notes are inaccurate):
 * For the "remove CLI option, settable via internal MCA" - Just remove them and confirm that it returns an "unrecognized option" error.
 * For deprecated options (or those that are renamed like `--timestamp-output`) give a deprecation warning and translate.
 * `--xterm` Historically this was a useful way to attach a `gdb` debugger to each process. So it does have a use. We decided to leave it in and someone should go and check that it works.

**Comment by rajachan** [comment]
@jjhursey, I am working on some low-hanging fruits in this list. I'd have to dive deeper, but doesn't look like test-suicide is a MCA param. I see https://github.com/openpmix/prrte/blob/master/src/mca/plm/base/plm_base_launch_support.c#L1791; is it supposed to be one?

**Comment by rhc54** [comment]
It certainly could be - it only impacts `prte` and isn't something you can run from `prun`, so no problem there. I think we didn't used to have it as an MCA param because it is only something a developer uses for test purposes, and we didn't want users seeing it in the equivalent of `ompi_info`. I would suggest keeping it as an envar and not an MCA param for that reason.

**Comment by rajachan** [comment]
Makes sense. Just making sure I understood the comment against that flag in Josh's summary: `--test-suicide remove CLI option, settable via internal MCA `

**Comment by rhc54** [comment]
I updated the comment

**Comment by rajachan** [comment]
Got distracted last week. Posted https://github.com/openpmix/prrte/pull/810

I had some changes for --debug too but dropped them after getting confused some. https://github.com/openpmix/prrte/issues/709#issuecomment-760489283 said we'd want to map --debug to -d and limit to the ompi personality, but I see --debug already being used for debug logging across personalities. Can someone clarify the exact behavior we want for that?

**Comment by rajachan** [comment]
@wckzhang and @dancejic will be posting changes for --output/--display.

**Comment by jjhursey** [comment]
For the `--debug` option - Let's discuss on the Teleconf this week if we don't sort it out beforehand.

I think the core question is do we want to preserve the behavior of:
 > `--debug` relaunches the launcher under the specified debugger.

If so then I propose we:
 * `--debug` relaunches the launcher under the specified debugger.
 * `-d` is the short form of `--debug`
 * The current PRRTE behavior of enabling debugging output with `--debug` would be tied to `--debug-devel`. This would mean that we preserve the `--debug-devel` option, but maybe make it not visible to the end user by default (if possible).

If we are open to renaming this option:
 * Can we rename `--debug` to `--debugger` to indicate that it is going to launch a (parallel) debugger?
 * Then keep `--debug` for additional debugging output.

Thoughts?

**Comment by jjhursey** [comment]
Per OpenPMIx Development Teleconf March 11, 2021:
 * Suggest removing the `--debug` behavior of `relaunching the launcher under the specified debugger`
   * `--debug` and `-d` will both enable debugging output in the PRRTE codebase. They will not relaunch a debugger (e.g., gdb).
 * Workaround for old behavior: If the user wants to launch with a debugger then they can manually wrap it around the `prun`/`prterun` command just as easily as the `--debug` option would with fork/exec.
 * Rationale: This reduces a fair amount of complexity from PRRTE for an option that is not easy to routinely test (meaning we may break it and not know for a long time). It is assumed that not many users actually use this option (can anyone refute that claim?).
 * Note that by changing the semantics `--debug` the Open MPI consumers of PRRTE will need to update their documentation ( [here for TotalView](https://www-lb.open-mpi.org/faq/?category=running#run-with-tv) and [here for DDT](https://www-lb.open-mpi.org/faq/?category=running#run-with-ddt) ) (FYI @jsquyres )
   * One alternative here is to remove the `--debug` option completely (and never use it), and create a `--debug-devel` for the debugging output in PRRTE.
   * Another alternative is that the OMPI personality throws a warning/error when the user passes `--debug` option to let them know that the old behavior is no longer supported.

Are there any objections or suggested modifications to this plan for PRRTE v2?

**Comment by jjhursey** [comment]
Based on some off-list discussions about `--debug` it is looking like the following proposal is what we are narrowing in on:
 - For Open MPI, mpirun with '-tv' and '--debug' will print an error message about the removal of support for those CLI options starting in Open MPI v5.
 - For PRRTE, we will use '--debug-devel' and '-d' to activate developer verbose logging in the run. We will make a note not to use the '--debug' option for at least one major version to avoid confusion (realistically, probably longer).
 - Open MPI will need to make some kind of document for end-users about the CLI changes moving from Open MPI v4 to v5 since we deprecated a number of CLI options to simplify the runtime. We will make sure to call out the removal of '-tv' and '--debug' in that Open MPI document and include how to activate the debugger without those options (this may require the MPIR-Shim).

**Comment by rajachan** [comment]
Thanks, I can write up the patch for the PRRTE change.

**Comment by jjhursey** [comment]
Per teleconf March 18, 2021
 * Keep `--report-pid` option. For when you have multiple jobs and need to attach to one of them this is a handy option to expose.

**Comment by jjhursey** [comment]
PR #866 adds the `--output` and `--display` options. Thanks @dancejic

**Comment by jjhursey** [comment]
Notes from March 25, 2021 Teleconf:
 * Lots of good work has been done here.
 * Can one of the contributors to this issue post a summary of what's been completed vs what is left to do in the next week?
   * This will help coordinate some activity around finishing this before we release v2.0.0 in a couple of weeks.

**Comment by rajachan** [comment]
@dancejic's PR https://github.com/openpmix/prrte/pull/891 adds --output and --display to the `ompi` personality and updates the deprecated options.

**Comment by rajachan** [comment]
https://github.com/openpmix/prrte/pull/914 fixes `-N` in the ompi personality.

**Comment by dancejic** [comment]
#954 deprecates the --debug option.

**Comment by rhc54** [comment]
This looks pretty much complete at this point.
