### ISSUE TITLE
prted: error while loading shared libaries when built with --enable-mca-static (new default)

### ISSUE THREAD

**Issue by acolinisi** [openpmix/prrte#871]
## Background information

PRRTE 1999b496bf02370804490a4ff1d7288426062947

### Please describe the system on which you are running

* Operating system/version: Gentoo Prefix
* Computer hardware: OLCF Summit

-----------------------------

With `--enable-mca-static`, which is the default since the following commit, prted fails to startup due to inability to load LSF libraries (despite LD_LIBRARY_PATH). Works fine with `--enable-mca-dso`. Presumably this is because in static mode, the ability to load dynamic libraries is lost completely. Perhaps this is by design, but making this the default breaks users who build against LFS or ALPS libraries.

The issue is the difficulty to diagnose this. The users don't get any error during the build, until at runtime, and the error is truly puzzling (since LD_LIBRARY_PATH doesn't help), and they need to somehow figure out that default ./configure arguments won't work for them and that they need to build with `--enable-mca-dso` (that is not at all obvious).

I was lucky that I already had everything working prior to this commit, so I just bisected after an update broke. Trying to diagnose this from scratch would be very difficult, because the connection between the error and the `--enable-mca-dso` flag is far from obvious.

```
commit 810557904daf8c740dd0c85e1664948408e94e76
Author: Brian Barrett <bbarrett@amazon.com>
Date:   Thu Mar 25 21:38:33 2021 +0000

    build: Change default build mode for components

```

```
$ mpirun -n 1 hostname
/<CUSTOM_PREFIX>/usr/bin/prted: error while loading shared libraries: libbat.so: cannot open shared object file: No such file or directory
--------------------------------------------------------------------------
PRTE was unable to reliably start one or more daemons.
```

The LSF libraries are in `/opt/ibm/spectrumcomputing/lsf/10.1.0.9/linux3.10-glibc2.17-ppc64le-csm/lib/`.

I doubt you are going to revert the default, and I have a workaround, so the purpose of this report is just for FYI purposes since the commit message mentioned something about users not using the shared library components (LFS or ALPS might be the important use case).

**Comment by rhc54** [comment]
That wasn't the intent - I thought we would have pulled in all the required dependencies for all built components.

@bwbarrett Any thoughts on this?

**Comment by rhc54** [comment]
@jsquyres

**Comment by jsquyres** [comment]
Ah shoot.  @rhc54 and I talked on the phone, and we think we know what's happening.  Give us a little time to figure out how to fix it.

**Comment by jjhursey** [comment]
I have a theory about what's going on here with the LSF side:
 * PRTE only uses the LSF library in the `plm/lsf` component which is exclusively run in the HPN (e.g., mpirun/prterun/prte).
 * LSF may not have installed this library on the compute nodes. Particularly for Summit where LSF does not exist on the compute nodes - only the launch nodes (where mpirun is run).
 * So the error is likely coming from the `prted` on the compute node failing to load because it is now staticly linked due to a component it would have never loaded.

The easiest short-term fix is to make the LSF components dynamic by default and not static. I'm not sure if @jsquyres or @rhc54 came up with something more clever than that.

**Comment by jjhursey** [comment]
After discussing this a bit offlist we came up with the following advice:
 * The default to build the LSF specific components (`plm/lsf`, `ess/lsf`, `ras/lsf`) as static should work fine for typical LSF deployments. We should keep that default for those systems.
 * The CORAL systems are not a typical LSF deployment because LSF is only available on the login and launch nodes. Not on the compute nodes. We have a configure mechanism to accommodate this configuration (`--enable-mca-dso`), as the OP mentioned.
   * The issue on this system seems to be coming from not having the LSF libraries on the compute nodes, but the `prted` on the compute node is now directly linked to the LSF libraries that, at runtime, it does not need.
   * Note that on this system the `plm/lsf` is not used. The component will [disqualify itself at runtime](https://github.com/openpmix/prrte/blob/499ee94efada68598d9e0844e8e2829618c31150/src/mca/plm/lsf/plm_lsf_component.c#L111) when it detects a CSM environment. This is because the LSF `blaunch` mechanism is not functional without the LSF daemons on the backend. Issue #804 talks a bit more about that
 * For the systems configured like the CORAL machines, Open MPI should request that the three LSF specific components be compiled shared.
   * You can do this with `./configure --enable-mca-dso=plm-lsf,ess-lsf,ras-lsf`
   * For the backend `prted` if they try to load any of these three components (which they shouldn't IIRC) the LSF shared objects will fail to load at runtime (and issue a warning that is suppressed by default with the other daemon output).

Action item:
 * We should document this in the Open MPI and PRRTE FAQ. I'll take an action item to add that documentation. We can keep this ticket open until that documentation is complete.
 * For this system, use `./configure --enable-mca-dso=plm-lsf,ess-lsf,ras-lsf` to return to the prior behavior.

**Comment by acolinisi** [comment]
Thanks, I think I follow. So the reason LD_LIBRARY_PATH was "not working" was simply that the path did not even exist on compute nodes; I failed to notice that. So, yeah, have to either link prted "indirectly" to the LFS libs (the `--enable-mca-dso` solution) or have to provide the libs on compute nodes by some means.

I haven't tried on ALPS yet, but do you predict that no issues will arise there since the ALPS libs are expected to be available on compute nodes?

**Comment by acolinisi** [comment]
Confirming that `--enable-mca-dso=plm-lsf,ess-lsf,ras-lsf` resolves this error too, no surprise.

**Comment by acolinisi** [comment]
@jjhursey  Documentation proposal: please consider adding a short note to description of `--with-lsf` in `./configure --help`: "Build LSF support. On some systems, may require --enable-mca-dso=plm-lsf,ess-lsf,ras-lsf (see FAQ)".

This would preclude stumbling on this issue. FAQ is good, but a note that's right next the flag would be a very good preventer. As a user, I'd just run `./configure --help`, search for LSF, find `--with-lsf` and enable it. I wouldn't pre-read FAQ to figure out what config flags I need to enable LSF, because it appears obvious from `--help`. So, then I'll get compile failures, and then I'd try to diagnose them, and maybe eventually try to search online, and maybe find the answer in FAQ. So, FAQ for better or worse often ends up far along this path, that we don't want to go down to begin with.

**Comment by rhc54** [comment]
We should hold off a bit on this as I'm encountering other issues related to this change. For example, on my Mac, I built PMIx configured `--with-curl=foo` to point at a non-standard location. The curl support is in the mca/common area, but is used by at least one plugin. It built fine, as did PRRTE when pointed at the PMIx installation. However, I was unable to run any PRRTE executable due to an inability to find a libcurl symbol. Reconfiguring PMIx without the curl support was the eventual workaround.

So I'm concerned that we may continue to keep running into these "gotchas" as we deploy. There are quite a few of the PMIx/PRRTE plugins that _could_ be static without issue as they clearly don't involve external libraries - PRRTE's rmap and routed components, for example. However, there are plugins that explicitly do have external dependencies - the launch and allocation ones, for example. These might well need to be dynamic.

Asking users to figure this out is probably not going to be popular and definitely a surprise. I'm wondering if we might need to revive a proposal from the original discussion on this feature that would allow the developers to specify a default "opt-out" policy for a plugin - essentially inverting the default on a per-plugin basis. This might be a better approach though it would clearly take some effort to develop.

If we decide to go that route and it would take some time to (a) find someone with the cycles to do it and then (b) actually implement it, I'd suggest that we revert this change in PMIx and PRRTE for the time being. I'm okay with leaving it if we can resolve the problem in the near-term before we release. OMPI's plugins don't generally have this system-dependency issue, so I think that side is in a little different situation.

@jsquyres @bwbarrett Make sense?

**Comment by rhc54** [comment]
I walked thru all the plugins and believe we are actually pretty good - almost none of them really have a reason to be dynamic as they don't rely on any external libs. There are a few, however, in both PMIx and PRRTE that break that pattern.

Rather than reverting or doing some fancy fix, I decided to do the simple thing and just list those few exceptions as the default for `--enable-mca-dso`:
```diff
diff --git a/config/pmix_mca.m4 b/config/pmix_mca.m4
index 15312f7..ddeb2f6 100644
--- a/config/pmix_mca.m4
+++ b/config/pmix_mca.m4
@@ -62,7 +62,8 @@ AC_DEFUN([PMIX_MCA],[
                         type-component pairs that will be built as
                         run-time loadable components (as opposed to
                         statically linked in), if supported on this
-                        platform.]))
+                        platform.]),
+                        [], [enable_mca_dso="pcompress-zlib,ploc-hwloc,pnet-opa,pnet-sshot,prm"])
     AC_ARG_ENABLE(mca-static,
         AS_HELP_STRING([--enable-mca-static=LIST],
                        [Comma-separated list of types and/or
```
and
```diff
diff --git a/config/prte_mca.m4 b/config/prte_mca.m4
index f884359..e3aa73a 100644
--- a/config/prte_mca.m4
+++ b/config/prte_mca.m4
@@ -62,7 +62,8 @@ AC_DEFUN([PRTE_MCA],[
                         type-component pairs that will be built as
                         run-time loadable components (as opposed to
                         statically linked in), if supported on this
-                        platform.]))
+                        platform.]),
+                        [], [enable_mca_dso=ess-alps,plm-alps,plm-lsf,plm-tm,ras-alps,ras-lsf])
     AC_ARG_ENABLE(mca-static,
         AS_HELP_STRING([--enable-mca-static=LIST],
                        [Comma-separated list of types and/or
diff --git a/src/mca/ess/lsf/Makefile.am b/src/mca/ess/lsf/Makefile.am
index b3a492b..02d718f 100644
--- a/src/mca/ess/lsf/Makefile.am
+++ b/src/mca/ess/lsf/Makefile.am
@@ -18,8 +18,8 @@
 #
 # $HEADER$
 #
-
-AM_CPPFLAGS = $(ess_lsf_CPPFLAGS)
+# The LSF plugin does not call any LSF library functions - it
+# therefore does NOT need to link against LSF libraries
 
 sources = \
         ess_lsf.h \
@@ -41,11 +41,9 @@ endif
 mcacomponentdir = $(prtelibdir)
 mcacomponent_LTLIBRARIES = $(component_install)
 mca_ess_lsf_la_SOURCES = $(sources)
-mca_ess_lsf_la_LDFLAGS = -module -avoid-version $(ess_lsf_LDFLAGS)
-mca_ess_lsf_la_LIBADD = $(ess_lsf_LIBS) \
-                        $(top_builddir)/src/libprrte.la
+mca_ess_lsf_la_LDFLAGS = -module -avoid-version
+mca_ess_lsf_la_LIBADD = $(top_builddir)/src/libprrte.la
 
 noinst_LTLIBRARIES = $(component_noinst)
 libmca_ess_lsf_la_SOURCES =$(sources)
-libmca_ess_lsf_la_LDFLAGS = -module -avoid-version $(ess_lsf_LDFLAGS)
-libmca_ess_lsf_la_LIBADD = $(ess_lsf_LIBS)
+libmca_ess_lsf_la_LDFLAGS = -module -avoid-version
diff --git a/src/mca/ras/slurm/Makefile.am b/src/mca/ras/slurm/Makefile.am
index c440fb8..74a7b1e 100644
--- a/src/mca/ras/slurm/Makefile.am
+++ b/src/mca/ras/slurm/Makefile.am
@@ -18,8 +18,8 @@
 #
 # $HEADER$
 #
-
-AM_CPPFLAGS = $(ras_slurm_CPPFLAGS)
+# The Slurm plugin does not call any Slurm functions - it therefore
+# does NOT need to link against any Slurm libraries
 
 dist_prtedata_DATA = help-ras-slurm.txt
 
@@ -48,11 +48,9 @@ endif
 mcacomponentdir = $(prtelibdir)
 mcacomponent_LTLIBRARIES = $(component)
 mca_ras_slurm_la_SOURCES = $(component_sources)
-mca_ras_slurm_la_LDFLAGS = -module -avoid-version $(ras_slurm_LDFLAGS)
-mca_ras_slurm_la_LIBADD = $(ras_slurm_LIBS) \
-                          $(top_builddir)/src/libprrte.la
+mca_ras_slurm_la_LDFLAGS = -module -avoid-version
+mca_ras_slurm_la_LIBADD = $(top_builddir)/src/libprrte.la
 
 noinst_LTLIBRARIES = $(lib)
 libmca_ras_slurm_la_SOURCES = $(lib_sources)
-libmca_ras_slurm_la_LDFLAGS = -module -avoid-version $(ras_slurm_LDFLAGS)
-libmca_ras_slurm_la_LIBADD = $(ras_slurm_LIBS)
+libmca_ras_slurm_la_LDFLAGS = -module -avoid-version
diff --git a/src/mca/ras/tm/Makefile.am b/src/mca/ras/tm/Makefile.am
index e066c3b..cf84477 100644
--- a/src/mca/ras/tm/Makefile.am
+++ b/src/mca/ras/tm/Makefile.am
@@ -18,14 +18,14 @@
 #
 # $HEADER$
 #
+# The TM plugin does not call any Torque/PBS functions - it therefore
+# does NOT need to link against any Torque/PBS libraries
 
 # Use the top-level Makefile.options
 
 dist_prtedata_DATA = help-ras-tm.txt
 
 
-AM_CPPFLAGS = $(ras_tm_CPPFLAGS)
-
 sources = \
         ras_tm.h \
         ras_tm_component.c \
@@ -51,11 +51,9 @@ endif
 mcacomponentdir = $(prtelibdir)
 mcacomponent_LTLIBRARIES = $(component)
 mca_ras_tm_la_SOURCES = $(component_sources)
-mca_ras_tm_la_LDFLAGS = -module -avoid-version $(ras_tm_LDFLAGS)
-mca_ras_tm_la_LIBADD = $(ras_tm_LIBS)  \
-                       $(top_builddir)/src/libprrte.la
+mca_ras_tm_la_LDFLAGS = -module -avoid-version
+mca_ras_tm_la_LIBADD = $(top_builddir)/src/libprrte.la
 
 noinst_LTLIBRARIES = $(lib)
 libmca_ras_tm_la_SOURCES = $(lib_sources)
-libmca_ras_tm_la_LDFLAGS = -module -avoid-version $(ras_tm_LDFLAGS)
-libmca_ras_tm_la_LIBADD = $(ras_tm_LIBS)
+libmca_ras_tm_la_LDFLAGS = -module -avoid-version
```
Note that in PRRTE we were unnecessarily linking in libraries to plugins that functionally had no such dependency.

Make sense?

**Comment by rhc54** [comment]
Sigh - should have checked further. This does not solve the `curl` failure I related previously as that is in mca/common. I suspect that problem is more of a bug, though, so perhaps the method is still valid.
